import type { Intervention } from './types';

/**
 * Mirrors the interventions from https://insight-payer.lovable.app/interventions
 * for Gen-AI agents to act on.
 */
export const INTERVENTIONS: Intervention[] = [
  {
    id: 'int-1',
    category: 'Adoption',
    merchantId: 'm5',
    merchantName: 'BigBasket (Tata)',
    mids: 1,
    priority: 'High Priority',
    title: 'BNPL Feature Activation — Only 8% Adoption Rate',
    description: 'BNPL integration completed 3 months ago but only 8% adoption rate. Requires promotional push and UI optimization.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'adoption',
  },
  {
    id: 'int-2',
    category: 'Cross-sell',
    merchantId: 'm1',
    merchantName: 'Zomato Media Pvt Ltd.',
    mids: 2,
    priority: 'High Priority',
    title: 'Instant Refunds & Loyalty Suite — Cross-sell Opportunity',
    description: 'Enable instant refunds for failed transactions and implement loyalty rewards program for repeat customers.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'crosssell',
  },
  {
    id: 'int-3',
    category: 'Volume Growth',
    merchantId: 'm3',
    merchantName: 'Swiggy Ltd.',
    mids: 4,
    priority: 'High Priority',
    title: 'Subscription Payments Not Enabled — Recurring Revenue Opportunity',
    description: 'Swiggy One has recurring billing potential. No e-mandate or SI integration active for subscription billing.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'volume',
  },
  {
    id: 'int-4',
    category: 'Cross-sell',
    merchantId: 'm4',
    merchantName: 'Flipkart Commerce',
    mids: 2,
    priority: 'High Priority',
    title: 'EMI Option Not Surfaced for High-Value Orders',
    description: 'Orders above ₹5,000 show 34% higher abandonment. No-cost EMI not visible at checkout for eligible products.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'crosssell',
  },
  {
    id: 'int-5',
    category: 'SR Recovery',
    merchantId: 'm4',
    merchantName: 'Flipkart Commerce',
    mids: 2,
    priority: 'Critical',
    title: 'UPI Success Rate Below Threshold — Routing Optimization Required',
    description: 'UPI SR dropped to 91.3% vs 96% benchmark. PSP routing failures on Razorpay causing 38% of declines.',
    actions: ['Pick Task', 'Root Cause', 'Play Book', 'Ignore'],
    agentId: 'sr-recovery',
  },
  {
    id: 'int-6',
    category: 'SR Recovery',
    merchantId: 'm2',
    merchantName: 'BookMyShow',
    mids: 1,
    priority: 'High Priority',
    title: 'Card 3DS Authentication Failure Spike on HDFC Gateway',
    description: '3DS failures increased 2.3x in last 72h. 28% of card declines traced to authentication timeouts on HDFC Cybersource.',
    actions: ['Pick Task', 'Root Cause', 'Play Book', 'Ignore'],
    agentId: 'sr-recovery',
  },
  {
    id: 'int-7',
    category: 'Adoption',
    merchantId: 'm4',
    merchantName: 'Flipkart Commerce',
    mids: 3,
    priority: 'High Priority',
    title: 'BNPL Feature Underutilized — Only 6% Checkout Penetration',
    description: 'Pay Later integration live for 4 months but only 6% of eligible users see the option. Industry avg is 22%.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'adoption',
  },
  {
    id: 'int-8',
    category: 'Adoption',
    merchantId: 'm2',
    merchantName: 'BookMyShow',
    mids: 1,
    priority: 'Medium',
    title: 'Card Tokenization Adoption at 28% — Below 60% Target',
    description: 'Only 28% of repeat card users have tokenized cards. Increases friction and reduces SR on repeat purchases.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'adoption',
  },
  {
    id: 'int-9',
    category: 'SR Recovery',
    merchantId: 'm3',
    merchantName: 'Swiggy Ltd.',
    mids: 1,
    priority: 'Medium',
    title: 'Net Banking Success Rate Degraded on SBI Channel',
    description: 'SBI net banking SR dropped 8% in last 5 days. Affecting 22% of net banking transactions.',
    actions: ['Pick Task', 'Root Cause', 'Play Book', 'Ignore'],
    agentId: 'sr-recovery',
  },
  {
    id: 'int-10',
    category: 'Volume Growth',
    merchantId: 'm1',
    merchantName: 'Zomato Media Pvt Ltd.',
    mids: 1,
    priority: 'Medium',
    title: 'International Card Acceptance Not Configured',
    description: 'Cross-border transactions being declined. No multi-currency support configured for international Visa/MC.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'volume',
  },
];
