import type { Intervention } from './types';

/**
 * Mirrors the interventions from https://insight-payer.lovable.app/interventions
 * for Gen-AI agents to act on.
 */
export const INTERVENTIONS: Intervention[] = [
  {
    id: 'int-1',
    category: 'Adoption',
    merchantId: 'm5',
    merchantName: 'BigBasket (Tata)',
    mids: 1,
    priority: 'High Priority',
    title: 'BNPL Feature Activation — Only 8% Adoption Rate',
    description: 'BNPL integration completed 3 months ago but only 8% adoption rate. Requires promotional push and UI optimization.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'adoption',
    aiImpact: 'Estimated +12–18% checkout conversion and ~₹2.1 Cr incremental GMV in 90 days if BNPL is surfaced at cart and in promos.',
    aiSuggestions: ['Surface BNPL at cart and payment step; A/B test placement.', 'Run a 2-week BNPL promo (e.g. no-cost EMI) and measure adoption.', 'Benchmark to grocery peer 22% adoption and close gap in 60 days.'],
  },
  {
    id: 'int-2',
    category: 'Cross-sell',
    merchantId: 'm1',
    merchantName: 'Zomato Media Pvt Ltd.',
    mids: 2,
    priority: 'High Priority',
    title: 'Instant Refunds & Loyalty Suite — Cross-sell Opportunity',
    description: 'Enable instant refunds for failed transactions and implement loyalty rewards program for repeat customers.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'crosssell',
    aiImpact: 'Instant refunds can reduce support tickets by ~25% and improve NPS; loyalty can lift repeat order rate by 15–20% and increase LTV.',
    aiSuggestions: ['Enable instant refunds for failed TXNs first (quick win).', 'Pilot loyalty with top 10% repeat users, then roll out.', 'Measure ticket volume and repeat rate before/after.'],
  },
  {
    id: 'int-3',
    category: 'Volume Growth',
    merchantId: 'm3',
    merchantName: 'Swiggy Ltd.',
    mids: 4,
    priority: 'High Priority',
    title: 'Subscription Payments Not Enabled — Recurring Revenue Opportunity',
    description: 'Swiggy One has recurring billing potential. No e-mandate or SI integration active for subscription billing.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'volume',
    aiImpact: 'E-mandate/SI for Swiggy One could add ~8–12% stable volume and improve retention; recurring revenue impact in range of ₹1.5–2 Cr/month.',
    aiSuggestions: ['Enable e-mandate for Swiggy One renewals on primary flow.', 'Default to auto-debit with clear consent and easy revocation.', 'Track mandate success rate and churn after go-live.'],
  },
  {
    id: 'int-4',
    category: 'Cross-sell',
    merchantId: 'm4',
    merchantName: 'Flipkart Commerce',
    mids: 2,
    priority: 'High Priority',
    title: 'EMI Option Not Surfaced for High-Value Orders',
    description: 'Orders above ₹5,000 show 34% higher abandonment. No-cost EMI not visible at checkout for eligible products.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'crosssell',
    aiImpact: 'Surfacing no-cost EMI for orders ₹5K+ could recover ~20–25% of high-value abandonments; estimated +₹8–12 Cr GMV in 60 days.',
    aiSuggestions: ['Show EMI eligibility and monthly amount on PDP and cart for ₹5K+.', 'A/B test EMI placement (above vs below pay button).', 'Monitor conversion and EMI mix for high-AOV segments.'],
  },
  {
    id: 'int-5',
    category: 'SR Recovery',
    merchantId: 'm4',
    merchantName: 'Flipkart Commerce',
    mids: 2,
    priority: 'Critical',
    title: 'UPI Success Rate Below Threshold — Routing Optimization Required',
    description: 'UPI SR dropped to 91.3% vs 96% benchmark. PSP routing failures on Razorpay causing 38% of declines.',
    actions: ['Pick Task', 'Root Cause', 'Play Book', 'Ignore'],
    agentId: 'sr-recovery',
    aiImpact: 'Restoring UPI SR to 96% can recover ~₹1.2 Cr revenue-at-risk weekly; routing fix typically shows effect within 5–7 days.',
    aiSuggestions: ['Run root-cause on Razorpay failures (timeouts vs bank declines).', 'Add fallback PSP for UPI or adjust timeout/retry policy.', 'Set alert if UPI SR drops below 94% for same-day response.'],
  },
  {
    id: 'int-6',
    category: 'SR Recovery',
    merchantId: 'm2',
    merchantName: 'BookMyShow',
    mids: 1,
    priority: 'High Priority',
    title: 'Card 3DS Authentication Failure Spike on HDFC Gateway',
    description: '3DS failures increased 2.3x in last 72h. 28% of card declines traced to authentication timeouts on HDFC Cybersource.',
    actions: ['Pick Task', 'Root Cause', 'Play Book', 'Ignore'],
    agentId: 'sr-recovery',
    aiImpact: 'Fixing 3DS timeouts can recover most of the 28% card declines; expect ~2–4% overall SR lift and lower customer drop-off at payment.',
    aiSuggestions: ['Check HDFC Cybersource timeout config and increase if needed.', 'Consider failover to alternate gateway for HDFC 3DS.', 'Monitor 3DS completion rate by bank and by gateway.'],
  },
  {
    id: 'int-7',
    category: 'Adoption',
    merchantId: 'm4',
    merchantName: 'Flipkart Commerce',
    mids: 3,
    priority: 'High Priority',
    title: 'BNPL Feature Underutilized — Only 6% Checkout Penetration',
    description: 'Pay Later integration live for 4 months but only 6% of eligible users see the option. Industry avg is 22%.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'adoption',
    aiImpact: 'Raising Pay Later visibility to 15–22% could add ~₹15–25 Cr GMV in 90 days; adoption lift typically visible in 4–6 weeks.',
    aiSuggestions: ['Show Pay Later where eligibility is clear (cart, payment step).', 'Run targeted campaign for high-intent, high-AOV users.', 'Compare placement and copy vs top-performing e-commerce peers.'],
  },
  {
    id: 'int-8',
    category: 'Adoption',
    merchantId: 'm2',
    merchantName: 'BookMyShow',
    mids: 1,
    priority: 'Medium',
    title: 'Card Tokenization Adoption at 28% — Below 60% Target',
    description: 'Only 28% of repeat card users have tokenized cards. Increases friction and reduces SR on repeat purchases.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'adoption',
    aiImpact: 'Moving tokenization from 28% to 60% can improve card SR by ~3–5% and reduce repeat-checkout friction; expect 8–12 weeks to reach target.',
    aiSuggestions: ['Prompt for save card (tokenize) after successful payment with clear benefit.', 'Pre-check “Save for next time” for returning users.', 'Track tokenization rate and card SR by cohort.'],
  },
  {
    id: 'int-9',
    category: 'SR Recovery',
    merchantId: 'm3',
    merchantName: 'Swiggy Ltd.',
    mids: 1,
    priority: 'Medium',
    title: 'Net Banking Success Rate Degraded on SBI Channel',
    description: 'SBI net banking SR dropped 8% in last 5 days. Affecting 22% of net banking transactions.',
    actions: ['Pick Task', 'Root Cause', 'Play Book', 'Ignore'],
    agentId: 'sr-recovery',
    aiImpact: 'Restoring SBI net banking SR can recover ~0.5–1% overall payment SR and reduce support load from net-banking failures.',
    aiSuggestions: ['Confirm with SBI/aggregator if there is an outage or config change.', 'Temporarily route part of SBI volume to backup path if available.', 'Monitor SBI SR daily until back to baseline.'],
  },
  {
    id: 'int-10',
    category: 'Volume Growth',
    merchantId: 'm1',
    merchantName: 'Zomato Media Pvt Ltd.',
    mids: 1,
    priority: 'Medium',
    title: 'International Card Acceptance Not Configured',
    description: 'Cross-border transactions being declined. No multi-currency support configured for international Visa/MC.',
    actions: ['Pick Task', 'Play Book', 'Ignore'],
    agentId: 'volume',
    aiImpact: 'Enabling international cards can capture inbound/outbound travel and NRI orders; potential +2–5% volume from international card segment.',
    aiSuggestions: ['Enable multi-currency and international Visa/MC on gateway.', 'Show “Pay in INR” or local currency where relevant.', 'Track international card volume and decline reasons post go-live.'],
  },
];
